//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package istiotypes

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSettingsApplication) DeepCopyInto(out *IstioSettingsApplication) {
	*out = *in
	in.IstioSettingsBase.DeepCopyInto(&out.IstioSettingsBase)
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(Retries)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSettingsApplication.
func (in *IstioSettingsApplication) DeepCopy() *IstioSettingsApplication {
	if in == nil {
		return nil
	}
	out := new(IstioSettingsApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSettingsBase) DeepCopyInto(out *IstioSettingsBase) {
	*out = *in
	in.Telemetry.DeepCopyInto(&out.Telemetry)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSettingsBase.
func (in *IstioSettingsBase) DeepCopy() *IstioSettingsBase {
	if in == nil {
		return nil
	}
	out := new(IstioSettingsBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestAuthentication) DeepCopyInto(out *RequestAuthentication) {
	*out = *in
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.TokenLocation != nil {
		in, out := &in.TokenLocation, &out.TokenLocation
		*out = new(string)
		**out = **in
	}
	if in.OutputClaimToHeaders != nil {
		in, out := &in.OutputClaimToHeaders, &out.OutputClaimToHeaders
		*out = new([]ClaimToHeader)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ClaimToHeader, len(*in))
			copy(*out, *in)
		}
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.IgnorePaths != nil {
		in, out := &in.IgnorePaths, &out.IgnorePaths
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestAuthentication.
func (in *RequestAuthentication) DeepCopy() *RequestAuthentication {
	if in == nil {
		return nil
	}
	out := new(RequestAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Retries) DeepCopyInto(out *Retries) {
	*out = *in
	if in.Attempts != nil {
		in, out := &in.Attempts, &out.Attempts
		*out = new(int32)
		**out = **in
	}
	if in.PerTryTimeout != nil {
		in, out := &in.PerTryTimeout, &out.PerTryTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RetryOnHttpResponseCodes != nil {
		in, out := &in.RetryOnHttpResponseCodes, &out.RetryOnHttpResponseCodes
		*out = new([]intstr.IntOrString)
		if **in != nil {
			in, out := *in, *out
			*out = make([]intstr.IntOrString, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Retries.
func (in *Retries) DeepCopy() *Retries {
	if in == nil {
		return nil
	}
	out := new(Retries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Telemetry) DeepCopyInto(out *Telemetry) {
	*out = *in
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = make([]*Tracing, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tracing)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry.
func (in *Telemetry) DeepCopy() *Telemetry {
	if in == nil {
		return nil
	}
	out := new(Telemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}
