version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    groups:
      nais-apis:
        patterns:
          - "github.com/nais/*"
      istio-io:
        patterns:
          - "istio.io/*"
      k8s-io:
        patterns:
          - "k8s.io/*"
    ignore:
      versions:
        - ".*-alpha.*"
        - ".*-beta.*"
        - ".*-rc.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
