project_name: skiperator

builds:
  - env:
      - CGO_ENABLED=0
    binary: bin/skiperator
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: i386
    tags:
      - osusergo
      - netgo
    main: ./cmd/skiperator/
    id: skiperator

archives:
  - id: default
    builds:
      - skiperator
    files:
      - README.md
      - CHANGELOG.md

dockers:
  - image_templates:
      - "ghcr.io/kartverket/skiperator"
    extra_files:
      - ./

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-dev"
changelog:
  sort: asc
