# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "skiperator"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "skip"
  system: "skip"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "skiperator"
  links:
  - url: "https://github.com/kartverket/skiperator"
    title: "skiperator på GitHub"
spec:
  type: "repo"
  owner: "skip"
  dependencyOf:
  - "component:skiperator"
