FROM --platform=$BUILDPLATFORM golang:1.26.3 AS base
# Needed for ca-certs

FROM scratch
ARG TARGETPLATFORM

COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
# Copy prebuilt binaries for that arch
COPY $TARGETPLATFORM/skiperator /skiperator

USER 65532:65532
ENTRYPOINT ["/skiperator"]
