//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package istiotypes

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimToHeader) DeepCopyInto(out *ClaimToHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimToHeader.
func (in *ClaimToHeader) DeepCopy() *ClaimToHeader {
	if in == nil {
		return nil
	}
	out := new(ClaimToHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSettings) DeepCopyInto(out *IstioSettings) {
	*out = *in
	in.Telemetry.DeepCopyInto(&out.Telemetry)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSettings.
func (in *IstioSettings) DeepCopy() *IstioSettings {
	if in == nil {
		return nil
	}
	out := new(IstioSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestAuth) DeepCopyInto(out *RequestAuth) {
	*out = *in
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.TokenLocation != nil {
		in, out := &in.TokenLocation, &out.TokenLocation
		*out = new(string)
		**out = **in
	}
	if in.OutputClaimToHeaders != nil {
		in, out := &in.OutputClaimToHeaders, &out.OutputClaimToHeaders
		*out = new([]ClaimToHeader)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ClaimToHeader, len(*in))
			copy(*out, *in)
		}
	}
	if in.AcceptedResources != nil {
		in, out := &in.AcceptedResources, &out.AcceptedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthRules != nil {
		in, out := &in.AuthRules, &out.AuthRules
		*out = new([]RequestAuthRule)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RequestAuthRule, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.IgnoreAuth != nil {
		in, out := &in.IgnoreAuth, &out.IgnoreAuth
		*out = new([]RequestMatcher)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RequestMatcher, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestAuth.
func (in *RequestAuth) DeepCopy() *RequestAuth {
	if in == nil {
		return nil
	}
	out := new(RequestAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestAuthRule) DeepCopyInto(out *RequestAuthRule) {
	*out = *in
	in.RequestMatcher.DeepCopyInto(&out.RequestMatcher)
	if in.When != nil {
		in, out := &in.When, &out.When
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestAuthRule.
func (in *RequestAuthRule) DeepCopy() *RequestAuthRule {
	if in == nil {
		return nil
	}
	out := new(RequestAuthRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestMatcher) DeepCopyInto(out *RequestMatcher) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestMatcher.
func (in *RequestMatcher) DeepCopy() *RequestMatcher {
	if in == nil {
		return nil
	}
	out := new(RequestMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Telemetry) DeepCopyInto(out *Telemetry) {
	*out = *in
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = make([]*Tracing, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tracing)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry.
func (in *Telemetry) DeepCopy() *Telemetry {
	if in == nil {
		return nil
	}
	out := new(Telemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}
