//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package identity_provider

import (
	"github.com/kartverket/skiperator/api/v1alpha1/istiotypes"
	v1 "github.com/nais/liberator/pkg/apis/nais.io/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraID) DeepCopyInto(out *EntraID) {
	*out = *in
	if in.AllowAllUsers != nil {
		in, out := &in.AllowAllUsers, &out.AllowAllUsers
		*out = new(bool)
		**out = **in
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = new(v1.AzureAdClaims)
		(*in).DeepCopyInto(*out)
	}
	if in.LogoutUrl != nil {
		in, out := &in.LogoutUrl, &out.LogoutUrl
		*out = new(string)
		**out = **in
	}
	if in.PreAuthorizedApplications != nil {
		in, out := &in.PreAuthorizedApplications, &out.PreAuthorizedApplications
		*out = make([]v1.AccessPolicyInboundRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReplyUrls != nil {
		in, out := &in.ReplyUrls, &out.ReplyUrls
		*out = make([]v1.AzureAdReplyUrl, len(*in))
		copy(*out, *in)
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyPrefix != nil {
		in, out := &in.SecretKeyPrefix, &out.SecretKeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.SecretProtected != nil {
		in, out := &in.SecretProtected, &out.SecretProtected
		*out = new(bool)
		**out = **in
	}
	if in.SinglePageApplication != nil {
		in, out := &in.SinglePageApplication, &out.SinglePageApplication
		*out = new(bool)
		**out = **in
	}
	if in.RequestAuth != nil {
		in, out := &in.RequestAuth, &out.RequestAuth
		*out = new(istiotypes.RequestAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraID.
func (in *EntraID) DeepCopy() *EntraID {
	if in == nil {
		return nil
	}
	out := new(EntraID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IDPorten) DeepCopyInto(out *IDPorten) {
	*out = *in
	if in.ClientName != nil {
		in, out := &in.ClientName, &out.ClientName
		*out = new(string)
		**out = **in
	}
	if in.AccessTokenLifetime != nil {
		in, out := &in.AccessTokenLifetime, &out.AccessTokenLifetime
		*out = new(int)
		**out = **in
	}
	if in.PostLogoutRedirectURIs != nil {
		in, out := &in.PostLogoutRedirectURIs, &out.PostLogoutRedirectURIs
		*out = new([]v1.IDPortenURI)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.IDPortenURI, len(*in))
			copy(*out, *in)
		}
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionLifetime != nil {
		in, out := &in.SessionLifetime, &out.SessionLifetime
		*out = new(int)
		**out = **in
	}
	if in.RequestAuth != nil {
		in, out := &in.RequestAuth, &out.RequestAuth
		*out = new(istiotypes.RequestAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IDPorten.
func (in *IDPorten) DeepCopy() *IDPorten {
	if in == nil {
		return nil
	}
	out := new(IDPorten)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maskinporten) DeepCopyInto(out *Maskinporten) {
	*out = *in
	if in.ClientName != nil {
		in, out := &in.ClientName, &out.ClientName
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = new(v1.MaskinportenScope)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestAuth != nil {
		in, out := &in.RequestAuth, &out.RequestAuth
		*out = new(istiotypes.RequestAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maskinporten.
func (in *Maskinporten) DeepCopy() *Maskinporten {
	if in == nil {
		return nil
	}
	out := new(Maskinporten)
	in.DeepCopyInto(out)
	return out
}
