apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  namespace: sample
  name: sample-one
spec:
  image: nginxinc/nginx-unprivileged
  port: 80
  labels:
    cascadeLabel: some-label
  resourceLabels:
    Deployment:
      deploymentLabel: another-label
    service:
      serviceLabel: yet-more-label
  ingresses:
    - test.com
  accessPolicy:
    inbound:
      rules:
        - application: sample-two
    outbound:
      rules:
        - namespace: sample
          application: sample-two
      external:
        - host: test.com
          ip: 12.43.31.12
