apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  namespace: sample
  name: sample-one
spec:
  image: "quay.io/brancz/prometheus-example-app:v0.4.0"

  port: 8080

  additionalPorts:
    - name: metrics-port
      port: 8181
      protocol: TCP
    - name: another-port
      port: 8282
      protocol: TCP

  command:
    - node
    - ./server.js

  ingresses:
    - testapp.dev.skip.statkart.no

  replicas:
    min: 3

    max: 5

    targetCpuUtilization: 80

  gcp:
    auth:
      serviceAccount: some-serviceaccount@some-project-id.iam.gserviceaccount.com

  env:
    - name: ENV
      value: PRODUCTION

    - name: USERNAME
      valueFrom:
        configMapKeyRef:
          name: some-configmap
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: some-secret
          key: password

  envFrom:
    - configMap: some-configmap
    - secret: some-secret

  filesFrom:
    - emptyDir: temp-dir
      mountPath: /test
    - configMap: some-configmap
      mountPath: /var/run/configmap
    - secret: some-secret
      mountPath: /var/run/secret
    - persistentVolumeClaim: some-pvc
      mountPath: /var/run/volume

  strategy:
    type: RollingUpdate

  liveness:
    path: /healthz

    port: 8080

    failureThreshold: 3

    timeout: 1

    initialDelay: 0

  labels:
    aaaah: some-label

  resourceLabels:
    Deployment:
      labelKey: test-test
    Service:
      labelKeyOne: test-one
      labelKeyTwo: test-two

  resources:
    limits:
      memory: 1G

    requests:
      cpu: 25m

      memory: 250M

  accessPolicy:
    inbound:
      rules:
        - application: other-app
        - application: third-app
          namespace: other-namespace

    outbound:
      rules:
        - application: sample-two

      external:
        - host: nrk.no

        - host: smtp.mailgrid.com

          ip: "123.123.123.123"

          ports:
            - name: smtp

              protocol: TCP
              port: 587
