apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: sample-app
data:
  nginx.conf: |
    worker_processes auto;
    
    error_log /tmp/nginx/error.log warn;
    pid       /tmp/nginx/nginx.pid;
    
    events {
      worker_connections 1024;
    }
    
    http {
      server {
        listen 8080;
        location / {
          add_header Content-Type text/plain;
          return 200 'hello world';
        }
      }
    }
