apiVersion: skiperator.kartverket.no/v1alpha1
kind: SKIPJob
metadata:
  namespace: sample
  name: sample-job-metrics
spec:
  container:
    image: perl:5.34.0
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
  prometheus:
    port: 8080
    path: "/metrics"