apiVersion: v1
kind: ConfigMap
metadata:
  name: skiperator-config
  namespace: skiperator-system
data:
  config.json: |
    {
      "topologyKeys": [
        "kubernetes.io/hostname",
        "onprem.gke.io/failure-domain-name"
      ]
    }
