apiVersion: skiperator.kartverket.no/v1alpha1
kind: SKIPJob
metadata:
  namespace: sample
  name: sample-job-cron
spec:
  container:
    image: perl:5.34.0
    command: ["perl",  "-Mbignum=bpi", "-wle", "exit 1"]

  cron:
    schedule: "* * * * *"

