name: write api-docs to skip.kartverket.no

on:
  push:

jobs:
  run-crdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: skiperator

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run crdoc Docker container
        run: |
          go install fybrik.io/crdoc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          crdoc --resources skiperator/config/crd --output api-docs.md

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          path: docs
          repository: kartverket/skip.kartverket.no
          ssh-key: ${{ secrets.SKIPDOCS_DEPLOY_KEY }}

      - name: Copy generated output to target repo
        run: |
          cp api-docs.md docs/docs/13-skiperator/04-api-docs.md  

      - name: Commit and push changes
        run: |
          cd docs
          git config --global user.email "skiperator@kartverket.no"
          git config --global user.name "GithubActions"
          git add .
          # Only commit if there are changes
          git diff --cached --exit-code
          if [ $? -eq 0 ]; then
            echo "No changes to commit"
          else
            git commit -m "Update Skiperator api-docs"
            git push origin main
          fi
