name: update api-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'config/crd/**'

concurrency:
  group: api-docs-update
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  run-crdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: skiperator

      - name: Run crdoc Docker container
        run: |
          mkdir -p crdoc-resources
          cp skiperator/config/crd/skiperator.kartverket.no_*.yaml crdoc-resources/
          docker run -u $(id -u):$(id -g) --rm -v $PWD:/workdir ghcr.io/fybrik/crdoc@sha256:355ef777a45021ee864e613b2234b4f2c6193762e3e0de94a26b66d06cec81c3 --resources /workdir/crdoc-resources --output /workdir/skiperator/api-docs.md --template /workdir/skiperator/.github/crdoc.tmpl
          rm -rf crdoc-resources

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          path: skiperator
          commit-message: "Update API docs"
          title: "Update generated API docs"
          body: |
            This PR updates the generated API documentation based on CRD changes.
            
            Triggered by: ${{ github.event_name }}
            Commit: ${{ github.sha }}
          branch: update/api-docs
          labels: |
            documentation
            automated
          delete-branch: true
