name: Deploy

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/skiperator-controller
          tags: type=sha,format=long
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        env:
          IMAGE: ghcr.io/kartverket/skiperator-controller:${{ steps.meta.outputs.version }}
        run: make push
    outputs:
      version: ${{ steps.meta.outputs.version }}

  sandbox:
    name: Deploy to sandbox
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v2.7.5
    needs: build
    with:
      runner: ubuntu-latest
      environment: sandbox
      kubernetes_cluster: atkv1-sandbox
      terraform_workspace: sandbox
      terraform_options: "-var=image=ghcr.io/kartverket/skiperator-controller:${{ needs.build.outputs.version }} -var-file=sandbox.tfvars"
      working_directory: deployment
      workload_identity_provider: projects/256430705282/locations/global/workloadIdentityPools/skiperator-deploy-pool/providers/github-provider
      service_account: skiperator-deploy@skip-sandbox-37c2.iam.gserviceaccount.com
      project_id: kubernetes-sandbox-6e24

  dev:
    name: Deploy to dev
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v2.7.5
    needs: [sandbox, build]
    with:
      runner: ubuntu-latest
      environment: dev
      kubernetes_cluster: atkv1-dev
      terraform_workspace: dev
      terraform_options: "-var=image=ghcr.io/kartverket/skiperator-controller:${{ needs.build.outputs.version }} -var-file=dev.tfvars"
      working_directory: deployment
      workload_identity_provider: projects/214581028419/locations/global/workloadIdentityPools/skiperator-deploy-pool/providers/github-provider
      service_account: skiperator-deploy@skip-dev-7d22.iam.gserviceaccount.com
      project_id: kubernetes-dev-94b9

  test:
    name: Deploy to test
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v2.7.5
    needs: [sandbox, build]
    with:
      runner: ubuntu-latest
      environment: test
      kubernetes_cluster: atkv1-test
      terraform_workspace: test
      terraform_options: "-var=image=ghcr.io/kartverket/skiperator-controller:${{ needs.build.outputs.version }} -var-file=test.tfvars"
      working_directory: deployment
      workload_identity_provider: projects/704673195983/locations/global/workloadIdentityPools/skiperator-deploy-pool/providers/github-provider
      service_account: skiperator-deploy@skip-test-b6e5.iam.gserviceaccount.com
      project_id: kubernetes-test-94f6

  prod:
    name: Deploy to prod
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v2.7.5
    needs: [sandbox, build]
    with:
      runner: ubuntu-latest
      environment: prod
      kubernetes_cluster: atkv1-prod
      terraform_workspace: prod
      terraform_options: "-var=image=ghcr.io/kartverket/skiperator-controller:${{ needs.build.outputs.version }} -var-file=prod.tfvars"
      working_directory: deployment
      workload_identity_provider: projects/421909719843/locations/global/workloadIdentityPools/skiperator-deploy-pool/providers/github-provider
      service_account: skiperator-deploy@skip-prod-bda1.iam.gserviceaccount.com
      project_id: kubernetes-prod-e4a2
