name: Deploy Skiperator Sandbox

on:
  workflow_dispatch:
    inputs:
      image_digest:
        description: "Image Digest of Skiperator version to deploy (sha:abc123.....)"
        required: true

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  RBAC_FILE_PATH: config/rbac/role.yaml
  CRD_APP_FILE_PATH: config/crd/skiperator.kartverket.no_applications.yaml
  CRD_JOB_FILE_PATH: config/crd/skiperator.kartverket.no_skipjobs.yaml
  ARTIFACT_NAME: skiperator-artifact-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  generate:
    name: CRD and ClusterRole
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Golang environment
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Generate CRD and ClusterRole
        run: make generate

      - name: Upload CRD and ClusterRole
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.RBAC_FILE_PATH }}
            ${{ env.CRD_APP_FILE_PATH }}
            ${{ env.CRD_JOB_FILE_PATH }}

  deploy-argo:
    needs: [generate]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base_dir: [./env/atkv3-sandbox/skiperator-system, ./env/atgcp1-sandbox/skiperator-system]
    env:
      TMP_FILE: tmp_kustomization.yaml
    steps:
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: kartverket/skip-apps
          identity: skiperator

      - name: Checkout apps repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: kartverket/skip-apps
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Download CRD and RBAC
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: config/

      - name: Patch Image Digest
        env:
          IMAGE_DIGEST: ${{ github.event.inputs.image_digest }}
        run: |
          kubectl patch --type=merge --local \
            -f ${{ matrix.base_dir }}/kustomization.yaml \
            -p "$(jq -nc --arg name "$REGISTRY/$IMAGE_NAME" --arg digest "$IMAGE_DIGEST" \
                  '{images:[{name:$name,digest:$digest}]}')" \
            -o yaml > ${{ matrix.base_dir }}/$TMP_FILE

          rm ${{ matrix.base_dir }}/kustomization.yaml
          mv ${{ matrix.base_dir }}/$TMP_FILE ${{ matrix.base_dir }}/kustomization.yaml

      - name: Update CRD and Role
        run: |
          cp -f -v $CRD_APP_FILE_PATH ${{ matrix.base_dir }}/patches/crd.yaml
          cp -f -v $CRD_JOB_FILE_PATH ${{ matrix.base_dir }}/patches/skipjob-crd.yaml
          cp -f -v $RBAC_FILE_PATH ${{ matrix.base_dir }}/patches/clusterrole.yaml
          rm -rf config/

      - name: Commit Changes to Repo
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          git config --global user.email "noreply@kartverket.no"
          git config --global user.name "GitHub Actions"
          git commit -am "deploy skiperator branch: $REF_NAME"
          git pull --rebase && git push
