name: Deploy Skiperator to sandbox manually

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to deploy to sandbox. Potential image tags are found under skiperator-controller packages."
        required: true
        type: string

jobs:
  sandbox:
    name: Deploy to sandbox
    permissions:
      id-token: write
      pull-requests: write
      contents: read
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@main
    with:
      runner: ubuntu-latest
      environment: sandbox
      kubernetes_cluster: atkv1-sandbox
      terraform_workspace: sandbox
      terraform_option_1: -var=image=ghcr.io/kartverket/skiperator-controller:${{ inputs.image_tag }}
      terraform_option_2: -var-file=sandbox.tfvars
      working_directory: deployment
      auth_project_number: 256430705282
      service_account: skiperator-deploy@skip-sandbox-37c2.iam.gserviceaccount.com
      project_id: kubernetes-sandbox-6e24
      deploy_on: ${{ github.ref }}
