name: write api-docs to skip.kartverket.no

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api-docs.md'
permissions:
  contents: write
  id-token: write

jobs:
  update-docs:
    name: Update skiperator documentation in skip.kartverket.no
    uses: kartverket/github-workflows/.github/workflows/update-skip-docs.yaml@fc9d6b1348c8ca79c77edfde133719970b4ef791
    with:
      source_path: "api-docs.md"
      target_path: "docs/03-applikasjon-utrulling/03-skiperator/04-api-docs.md"
      branch_name: "update-skiperator-docs-branch"
      author_name: "GithubActions <skiperator@kartverket.no>"
      identity: "skiperator"
